# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zhihu', '0002_auto_20160802_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='link',
            new_name='url',
        ),
    ]
