# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-20 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhihu', '0003_auto_20160803_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.CharField(default='', max_length=100),
        ),
    ]
