# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhihu', '0004_article_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='article',
            name='bio',
            field=models.CharField(default='', max_length=120),
        ),
    ]
