# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilibili', '0002_bangumi_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=120)),
                ('up', models.CharField(default='', max_length=25)),
                ('img', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
