# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-31 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilibili', '0003_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='bangumi',
            name='update_time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='update_time',
            field=models.CharField(default='', max_length=50),
        ),
    ]
