# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-04 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='message',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
